import { Inter } from "next/font/google";
import "./globals.css";
import TopBar from "../components/TopBar";
import SideNavBar from "@/components/SideNavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-start h-[100vh] overflow-y-scroll">
          <SideNavBar />
          <div className="w-full h-[100vh] overflow-y-scroll flex-1 main">
            <TopBar/>
            <div className="h-[100vh]">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
